const mongoose = require('mongoose');
const Test = mongoose.model('Test');
const axios = require('axios');

exports.getSymptoms = async (req, res) => {
  const symptoms =  {
    'abdominal_pain': 'Abdominal Pain',
    'abnormal_menstruation': 'Abnormal Menstruation',
    'acidity': 'Acidity',
    'acute_liver_failure': 'Acute Liver Failure',
    'altered_sensorium': 'Altered Sensorium',
    'anxiety': 'Anxiety',
    'back_pain': 'Back Pain',
    'belly_pain': 'Belly Pain',
    'blackheads': 'Blackheads',
    'bladder_discomfort': 'Bladder Discomfort',
    'blister': 'Blister',
    'blood_in_sputum': 'Blood In Sputum',
    'bloody_stool': 'Bloody Stool',
    'blurred_and_distorted_vision': 'Blurred And Distorted Vision',
    'breathlessness': 'Breathlessness',
    'brittle_nails': 'Brittle Nails',
    'bruising': 'Bruising',
    'burning_micturition': 'Burning Micturition',
    'chest_pain': 'Chest Pain',
    'chills': 'Chills',
    'cold_hands_and_feets': 'Cold Hands And Feets',
    'coma': 'Coma',
    'congestion': 'Congestion',
    'constipation': 'Constipation',
    'continuous_feel_of_urine': 'Continuous Feel Of Urine',
    'continuous_sneezing': 'Continuous Sneezing',
    'cough': 'Cough',
    'cramps': 'Cramps',
    'dark_urine': 'Dark Urine',
    'dehydration': 'Dehydration',
    'depression': 'Depression',
    'diarrhoea': 'Diarrhoea',
    'dischromic _patches': 'Dischromic  Patches',
    'distention_of_abdomen': 'Distention Of Abdomen',
    'dizziness': 'Dizziness',
    'drying_and_tingling_lips': 'Drying And Tingling Lips',
    'dry_cough': 'Dry Cough',
    'enlarged_thyroid': 'Enlarged Thyroid',
    'excessive_hunger': 'Excessive Hunger',
    'extra_marital_contacts': 'Extra Marital Contacts',
    'family_history': 'Family History',
    'fast_heart_rate': 'Fast Heart Rate',
    'fatigue': 'Fatigue',
    'fluid_overload': 'Fluid Overload',
    'fluid_overload.1': 'Fluid Overload.1',
    'foul_smell_of urine': 'Foul Smell Of Urine',
    'headache': 'Headache',
    'high_fever': 'High Fever',
    'hip_joint_pain': 'Hip Joint Pain',
    'history_of_alcohol_consumption': 'History Of Alcohol Consumption',
    'increased_appetite': 'Increased Appetite',
    'indigestion': 'Indigestion',
    'inflammatory_nails': 'Inflammatory Nails',
    'internal_itching': 'Internal Itching',
    'irregular_sugar_level': 'Irregular Sugar Level',
    'irritability': 'Irritability',
    'irritation_in_anus': 'Irritation In Anus',
    'itching': 'Itching',
    'joint_pain': 'Joint Pain',
    'knee_pain': 'Knee Pain',
    'lack_of_concentration': 'Lack Of Concentration',
    'lethargy': 'Lethargy',
    'loss_of_appetite': 'Loss Of Appetite',
    'loss_of_balance': 'Loss Of Balance',
    'loss_of_smell': 'Loss Of Smell',
    'malaise': 'Malaise',
    'mild_fever': 'Mild Fever',
    'mood_swings': 'Mood Swings',
    'movement_stiffness': 'Movement Stiffness',
    'mucoid_sputum': 'Mucoid Sputum',
    'muscle_pain': 'Muscle Pain',
    'muscle_wasting': 'Muscle Wasting',
    'muscle_weakness': 'Muscle Weakness',
    'nausea': 'Nausea',
    'neck_pain': 'Neck Pain',
    'nodal_skin_eruptions': 'Nodal Skin Eruptions',
    'obesity': 'Obesity',
    'pain_behind_the_eyes': 'Pain Behind The Eyes',
    'pain_during_bowel_movements': 'Pain During Bowel Movements',
    'pain_in_anal_region': 'Pain In Anal Region',
    'painful_walking': 'Painful Walking',
    'palpitations': 'Palpitations',
    'passage_of_gases': 'Passage Of Gases',
    'patches_in_throat': 'Patches In Throat',
    'phlegm': 'Phlegm',
    'polyuria': 'Polyuria',
    'prominent_veins_on_calf': 'Prominent Veins On Calf',
    'puffy_face_and_eyes': 'Puffy Face And Eyes',
    'pus_filled_pimples': 'Pus Filled Pimples',
    'receiving_blood_transfusion': 'Receiving Blood Transfusion',
    'receiving_unsterile_injections': 'Receiving Unsterile Injections',
    'red_sore_around_nose': 'Red Sore Around Nose',
    'red_spots_over_body': 'Red Spots Over Body',
    'redness_of_eyes': 'Redness Of Eyes',
    'restlessness': 'Restlessness',
    'runny_nose': 'Runny Nose',
    'rusty_sputum': 'Rusty Sputum',
    'scurring': 'Scurring',
    'shivering': 'Shivering',
    'silver_like_dusting': 'Silver Like Dusting',
    'sinus_pressure': 'Sinus Pressure',
    'skin_peeling': 'Skin Peeling',
    'skin_rash': 'Skin Rash',
    'slurred_speech': 'Slurred Speech',
    'small_dents_in_nails': 'Small Dents In Nails',
    'spinning_movements': 'Spinning Movements',
    'spotting_ urination': 'Spotting  Urination',
    'stiff_neck': 'Stiff Neck',
    'stomach_bleeding': 'Stomach Bleeding',
    'stomach_pain': 'Stomach Pain',
    'sunken_eyes': 'Sunken Eyes',
    'sweating': 'Sweating',
    'swelled_lymph_nodes': 'Swelled Lymph Nodes',
    'swelling_joints': 'Swelling Joints',
    'swelling_of_stomach': 'Swelling Of Stomach',
    'swollen_blood_vessels': 'Swollen Blood Vessels',
    'swollen_extremeties': 'Swollen Extremeties',
    'swollen_legs': 'Swollen Legs',
    'throat_irritation': 'Throat Irritation',
    'toxic_look_(typhos)': 'Toxic Look (Typhos)',
    'ulcers_on_tongue': 'Ulcers On Tongue',
    'unsteadiness': 'Unsteadiness',
    'visual_disturbances': 'Visual Disturbances',
    'vomiting': 'Vomiting',
    'watering_from_eyes': 'Watering From Eyes',
    'weakness_in_limbs': 'Weakness In Limbs',
    'weakness_of_one_body_side': 'Weakness Of One Body Side',
    'weight_gain': 'Weight Gain',
    'weight_loss': 'Weight Loss',
    'yellow_crust_ooze': 'Yellow Crust Ooze',
    'yellow_urine': 'Yellow Urine',
    'yellowing_of_eyes': 'Yellowing Of Eyes',
    'yellowish_skin': 'Yellowish Skin',
  }
  const diseases = {
    1 :"Jaundice",
    2 :"Hepatitis E",
    3 :"Hepatitis C",
    4 :"Hepatitis A",
    5 :"Tuberculosis",
    6 :"Impetigo",
    7 :"Paroymsal  Positional Vertigo",
    8 :"Common Cold",
    9 :"Varicose veins",
    10 :"Osteoarthristis",
    11 :"Pneumonia",
    12 :"Hyperthyroidism",
    13 :"Migraine",
    14 :"Drug Reaction",
    15 :"Psoriasis",
    16 :"Hypoglycemia",
    17 :"Chicken pox",
    18 :"Hepatitis B",
    19 :"Diabetes",
    20 :"Peptic ulcer diseae",
    21 :"Arthritis",
    22 :"Dengue",
    23 :"Hepatitis D",
    24 :"Malaria",
    25 :"Typhoid",
    26 :"Bronchial Asthma",
    27 :"COVID-19",
    28 :"Cervical spondylosis",
    29 :"Chronic cholestasis",
    30 :"Hypertension",
    31 :"Dimorphic hemmorhoids(piles)",
    32 :"Hypothyroidism",
    33 :"Alcoholic hepatitis",
    34 :"GERD",
    35 :"Urinary tract infection",
    36 :"Gastroenteritis",
    37 :"Fungal infection",
    38 :"AIDS",
    39 :"Acne",
    40 :"Allergy"
  }
  res.json({
      message: "Get Symptoms list",
      data: {
        symptoms,
        diseases
      }
  });
};

exports.getSymptomsList = async (req, res) => {
  const symptoms =  [
    'Abdominal Pain',
    'Abnormal Menstruation',
    'Acidity',
    'Acute Liver Failure',
    'Altered Sensorium',
    'Anxiety',
    'Back Pain',
    'Belly Pain',
    'Blackheads',
    'Bladder Discomfort',
    'Blister',
    'Blood In Sputum',
    'Bloody Stool',
    'Blurred And Distorted Vision',
    'Breathlessness',
    'Brittle Nails',
    'Bruising',
    'Burning Micturition',
    'Chest Pain',
    'Chills',
    'Cold Hands And Feets',
    'Coma',
    'Congestion',
    'Constipation',
    'Continuous Feel Of Urine',
    'Continuous Sneezing',
    'Cough',
    'Cramps',
    'Dark Urine',
    'Dehydration',
    'Depression',
    'Diarrhoea',
    'Dischromic  Patches',
    'Distention Of Abdomen',
    'Dizziness',
    'Drying And Tingling Lips',
    'Dry Cough',
    'Enlarged Thyroid',
    'Excessive Hunger',
    'Extra Marital Contacts',
    'Family History',
    'Fast Heart Rate',
    'Fatigue',
    'Fluid Overload',
    'Fluid Overload.1',
    'Foul Smell Of Urine',
    'Headache',
    'High Fever',
    'Hip Joint Pain',
    'History Of Alcohol Consumption',
    'Increased Appetite',
    'Indigestion',
    'Inflammatory Nails',
    'Internal Itching',
    'Irregular Sugar Level',
    'Irritability',
    'Irritation In Anus',
    'Itching',
    'Joint Pain',
    'Knee Pain',
    'Lack Of Concentration',
    'Lethargy',
    'Loss Of Appetite',
    'Loss Of Balance',
    'Loss Of Smell',
    'Malaise',
    'Mild Fever',
    'Mood Swings',
    'Movement Stiffness',
    'Mucoid Sputum',
    'Muscle Pain',
    'Muscle Wasting',
    'Muscle Weakness',
    'Nausea',
    'Neck Pain',
    'Nodal Skin Eruptions',
    'Obesity',
    'Pain Behind The Eyes',
    'Pain During Bowel Movements',
    'Pain In Anal Region',
    'Painful Walking',
    'Palpitations',
    'Passage Of Gases',
    'Patches In Throat',
    'Phlegm',
    'Polyuria',
    'Prominent Veins On Calf',
    'Puffy Face And Eyes',
    'Pus Filled Pimples',
    'Receiving Blood Transfusion',
    'Receiving Unsterile Injections',
    'Red Sore Around Nose',
    'Red Spots Over Body',
    'Redness Of Eyes',
    'Restlessness',
    'Runny Nose',
    'Rusty Sputum',
    'Scurring',
    'Shivering',
    'Silver Like Dusting',
    'Sinus Pressure',
    'Skin Peeling',
    'Skin Rash',
    'Slurred Speech',
    'Small Dents In Nails',
    'Spinning Movements',
    'Spotting  Urination',
    'Stiff Neck',
    'Stomach Bleeding',
    'Stomach Pain',
    'Sunken Eyes',
    'Sweating',
    'Swelled Lymph Nodes',
    'Swelling Joints',
    'Swelling Of Stomach',
    'Swollen Blood Vessels',
    'Swollen Extremeties',
    'Swollen Legs',
    'Throat Irritation',
    'Toxic Look (Typhos)',
    'Ulcers On Tongue',
    'Unsteadiness',
    'Visual Disturbances',
    'Vomiting',
    'Watering From Eyes',
    'Weakness In Limbs',
    'Weakness Of One Body Side',
    'Weight Gain',
    'Weight Loss',
    'Yellow Crust Ooze',
    'Yellow Urine',
    'Yellowing Of Eyes',
    'Yellowish Skin'
  ]
  res.json({
      message: "Get Symptoms list",
      data: {
        symptoms
      }
  });
};

exports.predictFromSymptoms = async (req,res) => {
  const { symptoms } = req.body;
  const response = await axios.post('https://medtech-ml.herokuapp.com/predict', {
    symptoms
  });
  
  res.json({
      message: "Predicted disease from symptoms",
      data: {
        predictions: response.data,
      }
  });
};

exports.predictDisease = async (req,res) => {
  const { symptoms } = req.body;

  const symptomList =  {
    'abdominal_pain': 'Abdominal Pain',
    'abnormal_menstruation': 'Abnormal Menstruation',
    'acidity': 'Acidity',
    'acute_liver_failure': 'Acute Liver Failure',
    'altered_sensorium': 'Altered Sensorium',
    'anxiety': 'Anxiety',
    'back_pain': 'Back Pain',
    'belly_pain': 'Belly Pain',
    'blackheads': 'Blackheads',
    'bladder_discomfort': 'Bladder Discomfort',
    'blister': 'Blister',
    'blood_in_sputum': 'Blood In Sputum',
    'bloody_stool': 'Bloody Stool',
    'blurred_and_distorted_vision': 'Blurred And Distorted Vision',
    'breathlessness': 'Breathlessness',
    'brittle_nails': 'Brittle Nails',
    'bruising': 'Bruising',
    'burning_micturition': 'Burning Micturition',
    'chest_pain': 'Chest Pain',
    'chills': 'Chills',
    'cold_hands_and_feets': 'Cold Hands And Feets',
    'coma': 'Coma',
    'congestion': 'Congestion',
    'constipation': 'Constipation',
    'continuous_feel_of_urine': 'Continuous Feel Of Urine',
    'continuous_sneezing': 'Continuous Sneezing',
    'cough': 'Cough',
    'cramps': 'Cramps',
    'dark_urine': 'Dark Urine',
    'dehydration': 'Dehydration',
    'depression': 'Depression',
    'diarrhoea': 'Diarrhoea',
    'dischromic _patches': 'Dischromic  Patches',
    'distention_of_abdomen': 'Distention Of Abdomen',
    'dizziness': 'Dizziness',
    'drying_and_tingling_lips': 'Drying And Tingling Lips',
    'dry_cough': 'Dry Cough',
    'enlarged_thyroid': 'Enlarged Thyroid',
    'excessive_hunger': 'Excessive Hunger',
    'extra_marital_contacts': 'Extra Marital Contacts',
    'family_history': 'Family History',
    'fast_heart_rate': 'Fast Heart Rate',
    'fatigue': 'Fatigue',
    'fluid_overload': 'Fluid Overload',
    'fluid_overload.1': 'Fluid Overload.1',
    'foul_smell_of urine': 'Foul Smell Of Urine',
    'headache': 'Headache',
    'high_fever': 'High Fever',
    'hip_joint_pain': 'Hip Joint Pain',
    'history_of_alcohol_consumption': 'History Of Alcohol Consumption',
    'increased_appetite': 'Increased Appetite',
    'indigestion': 'Indigestion',
    'inflammatory_nails': 'Inflammatory Nails',
    'internal_itching': 'Internal Itching',
    'irregular_sugar_level': 'Irregular Sugar Level',
    'irritability': 'Irritability',
    'irritation_in_anus': 'Irritation In Anus',
    'itching': 'Itching',
    'joint_pain': 'Joint Pain',
    'knee_pain': 'Knee Pain',
    'lack_of_concentration': 'Lack Of Concentration',
    'lethargy': 'Lethargy',
    'loss_of_appetite': 'Loss Of Appetite',
    'loss_of_balance': 'Loss Of Balance',
    'loss_of_smell': 'Loss Of Smell',
    'malaise': 'Malaise',
    'mild_fever': 'Mild Fever',
    'mood_swings': 'Mood Swings',
    'movement_stiffness': 'Movement Stiffness',
    'mucoid_sputum': 'Mucoid Sputum',
    'muscle_pain': 'Muscle Pain',
    'muscle_wasting': 'Muscle Wasting',
    'muscle_weakness': 'Muscle Weakness',
    'nausea': 'Nausea',
    'neck_pain': 'Neck Pain',
    'nodal_skin_eruptions': 'Nodal Skin Eruptions',
    'obesity': 'Obesity',
    'pain_behind_the_eyes': 'Pain Behind The Eyes',
    'pain_during_bowel_movements': 'Pain During Bowel Movements',
    'pain_in_anal_region': 'Pain In Anal Region',
    'painful_walking': 'Painful Walking',
    'palpitations': 'Palpitations',
    'passage_of_gases': 'Passage Of Gases',
    'patches_in_throat': 'Patches In Throat',
    'phlegm': 'Phlegm',
    'polyuria': 'Polyuria',
    'prominent_veins_on_calf': 'Prominent Veins On Calf',
    'puffy_face_and_eyes': 'Puffy Face And Eyes',
    'pus_filled_pimples': 'Pus Filled Pimples',
    'receiving_blood_transfusion': 'Receiving Blood Transfusion',
    'receiving_unsterile_injections': 'Receiving Unsterile Injections',
    'red_sore_around_nose': 'Red Sore Around Nose',
    'red_spots_over_body': 'Red Spots Over Body',
    'redness_of_eyes': 'Redness Of Eyes',
    'restlessness': 'Restlessness',
    'runny_nose': 'Runny Nose',
    'rusty_sputum': 'Rusty Sputum',
    'scurring': 'Scurring',
    'shivering': 'Shivering',
    'silver_like_dusting': 'Silver Like Dusting',
    'sinus_pressure': 'Sinus Pressure',
    'skin_peeling': 'Skin Peeling',
    'skin_rash': 'Skin Rash',
    'slurred_speech': 'Slurred Speech',
    'small_dents_in_nails': 'Small Dents In Nails',
    'spinning_movements': 'Spinning Movements',
    'spotting_ urination': 'Spotting  Urination',
    'stiff_neck': 'Stiff Neck',
    'stomach_bleeding': 'Stomach Bleeding',
    'stomach_pain': 'Stomach Pain',
    'sunken_eyes': 'Sunken Eyes',
    'sweating': 'Sweating',
    'swelled_lymph_nodes': 'Swelled Lymph Nodes',
    'swelling_joints': 'Swelling Joints',
    'swelling_of_stomach': 'Swelling Of Stomach',
    'swollen_blood_vessels': 'Swollen Blood Vessels',
    'swollen_extremeties': 'Swollen Extremeties',
    'swollen_legs': 'Swollen Legs',
    'throat_irritation': 'Throat Irritation',
    'toxic_look_(typhos)': 'Toxic Look (Typhos)',
    'ulcers_on_tongue': 'Ulcers On Tongue',
    'unsteadiness': 'Unsteadiness',
    'visual_disturbances': 'Visual Disturbances',
    'vomiting': 'Vomiting',
    'watering_from_eyes': 'Watering From Eyes',
    'weakness_in_limbs': 'Weakness In Limbs',
    'weakness_of_one_body_side': 'Weakness Of One Body Side',
    'weight_gain': 'Weight Gain',
    'weight_loss': 'Weight Loss',
    'yellow_crust_ooze': 'Yellow Crust Ooze',
    'yellow_urine': 'Yellow Urine',
    'yellowing_of_eyes': 'Yellowing Of Eyes',
    'yellowish_skin': 'Yellowish Skin',
  }

  function getKeyByValue(value) {
    return Object.keys(symptomList).find(key => symptomList[key] === value);
  }

  var arr = symptoms.map(item => {
    return getKeyByValue(item)
  })

  const response = await axios.post('https://medtech-ml.herokuapp.com/predict', {
    symptoms: arr
  });
  
  res.json({
      message: "Predicted disease from symptoms",
      data: {
        predictions: response.data,
      }
  });
};

exports.putOutcome = async (req, res) => {
  const { symptoms, outcome, predictions, disease } = req.body;

  const test = new Test({
    symptoms
  });

  if(disease) {
    test.disease = disease;
  }

  if(predictions) {
    test.predictions = predictions;
  }

  if(outcome) {
    test.outcome = outcome;
  }

  await test.save();

  res.json({
    message: "Outcome stored"      
  });
}